### ISSUE TITLE
Enquiry Regarding OpenGenus OpenSouce Internship Program

### ISSUE THREAD

**Issue by Shreyas-SAS** [OpenGenus/API-with-tRPC#1]
Hello! @AdiChat ,
This wouldn't be the best place to message, but I would like to ask something. 
I would like to know if the OpenSource Program by OpenGenus is still active and whether I can participate. 
I have replied on the website [OpenGenus](https://discourse.opengenus.org/t/internship-guidelines-at-opengenus/2335) should I wait now for the mentors to contact me, or has the procedure changed over the years?

**Comment by AdiChat** [comment]
Yes, it is active. We have started our Internship thread with you on our forum :+1:
